<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="FAQS.aspx.vb" Inherits="FAQS" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
  <link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="font-awesome/css/font-awesome.min.css" />

    <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

<div class="page-header">
    <h1>Preguntas Frecuentes <small>FAQS</small></h1>
</div>

<!-- Bootstrap FAQ - START -->
<div class="container">
    <br />
    <br />
    <br />

    
    <br />

    <div class="panel-group" id="accordion">
        <div class="faqHeader">Preguntas Generales</div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Como creo mi cuenta?</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                   El registro a <strong>Fightshop</strong> es requisito para poder comprar en el ECommerce. 
                    Esto asegura fiabilidad entre los usuarios.
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTen">Olvide mi contraseña</a>
                </h4>
            </div>
            <div id="collapseTen" class="panel-collapse collapse">
                <div class="panel-body">
                    No hay problema !, Enviaremos tu contraseña aleatoria al instante, solo ingresa tu correo electronico para poder comunicarnos.       </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven">En que moneda se trabaja para las transacciones?</a>
                </h4>
            </div>
            <div id="collapseEleven" class="panel-collapse collapse">
                <div class="panel-body">
                   Todos los precios se encuentran segun moneda Peso Argentino. <strong>AR$</strong>
                </div>
            </div>
        </div>

         <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven">Medios de Pago?</a>
                </h4>
            </div>
            <div id="collapseEleven" class="panel-collapse collapse">
                <div class="panel-body">
                   <div class="wrap-content" style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , sans-serif; margin: 0px 0px 35px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 300; font-stretch: inherit; font-size: 17px; line-height: inherit; color: rgb(51, 51, 51); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="responsive-table" style="box-sizing: border-box; font: inherit; margin: 10px 0px 0px; padding: 0px 0px 0px 1px; border: 0px; outline: 0px; vertical-align: baseline; overflow: visible; position: relative;">
                        <div class="column-fixed" style="box-sizing: border-box; font: inherit; margin: 0px 0px 0px -1px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; overflow-y: visible;">
                            <table class="ch-datagrid" style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border: none; outline: 0px; vertical-align: baseline; border-collapse: collapse; border-spacing: 0px; width: 499px; text-align: left;" summary="Cómo pagar tu compra">
                                <tbody style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline;">
                                    <tr style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(222, 222, 222); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; vertical-align: baseline;">
                                        <td class="responsive-table-listing" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: rgb(222, 222, 222); border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center; left: 0px; width: 120px; background-color: rgb(255, 255, 255);">
                                            <ul style="box-sizing: border-box; font-family: inherit; margin: 10px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; list-style: disc inside; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.2;">
                                                <li class="paymentmethod-visa" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -49px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); width: 39px; height: 16px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Visa<span>&nbsp;</span></li>
                                                <li class="paymentmethod-master" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -100px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 26px; width: 30px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Mastercard<span>&nbsp;</span></li>
                                                <li class="paymentmethod-amex" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -150px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 17px; width: 17px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">American Express</li>
                                                <li class="paymentmethod-HomeFixpago_cc" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -1047px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 20px; width: 30px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">HomeFix + Banco Patagonia<span>&nbsp;</span></li>
                                                <li class="paymentmethod-naranja" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -300px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 22px; width: 16px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Naranja<span>&nbsp;</span></li>
                                                <li class="paymentmethod-argencard" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -550px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 18px; width: 17px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Argencard<span>&nbsp;</span></li>
                                                <li class="paymentmethod-cabal" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -500px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 17px; width: 17px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Cabal</li>
                                                <li class="paymentmethod-cencosud" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -450px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 17px; width: 26px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Cencosud<span>&nbsp;</span></li>
                                                <li class="paymentmethod-nativa" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -350px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 15px; width: 36px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Nativa<span>&nbsp;</span></li>
                                                <li class="paymentmethod-tarshop" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -400px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); width: 27px; height: 16px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Tarjeta Shopping<span>&nbsp;</span></li>
                                                <li class="paymentmethod-cordobesa" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -998px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 10px; width: 40px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Cordobesa<span>&nbsp;</span></li>
                                                <li class="paymentmethod-cmr" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -949px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 19px; width: 26px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">CMR<span>&nbsp;</span></li>
                                                <li class="paymentmethod-cordial" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -898px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 21px; width: 30px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Cordial</li>
                                            </ul>
                                            <p style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , arial, helvetica, &quot; nimbus sans l&quot; , sans-serif; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.4; color: rgb(51, 51, 51);">
                                                <strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">Tarjeta de crédito</strong>.
                                            </p>
                                        </td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px 0px 0px -1px; padding: 10px; border-top: 0px; border-right: 1px solid rgb(222, 222, 222); border-bottom: 1px solid rgb(222, 222, 222); border-left: none; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">Hasta<span>&nbsp;</span><strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">12 cuotas sin interés</strong><span>&nbsp;</span>con<span>&nbsp;</span> promociones 
                                            bancarias<p style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , arial, helvetica, &quot; nimbus sans l&quot; , sans-serif; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.4; color: rgb(51, 51, 51);">
                                                Costo de financiación para pagos con tarjetas de crédito
                                            </p>
                                        </td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: initial; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">Se acredita instantáneamente</td>
                                    </tr>
                                    <tr style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(222, 222, 222); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; vertical-align: baseline;">
                                        <td class="responsive-table-listing" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: rgb(222, 222, 222); border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center; left: 0px; width: 120px; background-color: rgb(255, 255, 255);">
                                            <ul class="payment-method-list" style="box-sizing: border-box; font-family: inherit; margin: 10px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; list-style: disc inside; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.2;">
                                                <li class="paymentmethod-visa" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -49px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); width: 39px; height: 16px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Visa<span>&nbsp;</span></li>
                                                <li class="paymentmethod-maestro" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -1197px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 25px; width: 30px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Maestro<span>&nbsp;</span></li>
                                                <li class="paymentmethod-debcabal" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -1298px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 17px; width: 17px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Cabal</li>
                                            </ul>
                                            <p style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , arial, helvetica, &quot; nimbus sans l&quot; , sans-serif; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.4; color: rgb(51, 51, 51);">
                                                <strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">Tarjeta</strong><span>&nbsp;</span><strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">dedébito.</strong>
                                            </p>
                                        </td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px 0px 0px -1px; padding: 10px; border-top: 0px; border-right: 1px solid rgb(222, 222, 222); border-bottom: 1px solid rgb(222, 222, 222); border-left: none; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">1 pago</td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: initial; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">Se acredita instantáneamente</td>
                                    </tr>
                                    <tr style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(222, 222, 222); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; vertical-align: baseline;">
                                        <td class="responsive-table-listing" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: rgb(222, 222, 222); border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center; left: 0px; width: 120px; background-color: rgb(255, 255, 255);">
                                            <ul class="payment-method-list" style="box-sizing: border-box; font-family: inherit; margin: 10px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; list-style: disc inside; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.2;">
                                                <li class="paymentmethod-rapipago" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -650px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 11px; width: 56px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Rapipago<span>&nbsp;</span></li>
                                                <li class="paymentmethod-pagofacil" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -600px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 20px; width: 19px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Pago Fácil<span>&nbsp;</span></li>
                                                <li class="paymentmethod-cargavirtual" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -849px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 20px; width: 20px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Carga Virtual</li>
                                            </ul>
                                            <p style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , arial, helvetica, &quot; nimbus sans l&quot; , sans-serif; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.4; color: rgb(51, 51, 51);">
                                                <strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">En</strong><span>&nbsp;</span><strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">efectivo<span>&nbsp;</span></strong>con<strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">Rapipago</strong>,<strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;"><span>&nbsp;</span>Pago 
                                                Fácil</strong><span>&nbsp;</span>y<strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;"><span>&nbsp;</span>Carga Virtual</strong>: te&nbsp;damos un número para pagar.
                                            </p>
                                        </td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px 0px 0px -1px; padding: 10px; border-top: 0px; border-right: 1px solid rgb(222, 222, 222); border-bottom: 1px solid rgb(222, 222, 222); border-left: none; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">1 pago</td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: initial; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">Se acredita instantáneamente</td>
                                    </tr>
                                    <tr style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(222, 222, 222); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; vertical-align: baseline;">
                                        <td class="responsive-table-listing" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: rgb(222, 222, 222); border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center; left: 0px; width: 120px; background-color: rgb(255, 255, 255);">
                                            <ul style="box-sizing: border-box; font-family: inherit; margin: 10px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; list-style: disc inside; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.2;">
                                                <li class="paymentmethod-redlink" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -700px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 20px; width: 19px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Red Link</li>
                                            </ul>
                                            <p style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , arial, helvetica, &quot; nimbus sans l&quot; , sans-serif; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.4; color: rgb(51, 51, 51);">
                                                <strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">Transferencia bancaria&nbsp;</strong>con<strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">Red Link</strong>: pagá desde tu homebanking o cajero automático.
                                            </p>
                                        </td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px 0px 0px -1px; padding: 10px; border-top: 0px; border-right: 1px solid rgb(222, 222, 222); border-bottom: 1px solid rgb(222, 222, 222); border-left: none; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">1 pago</td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: initial; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">Pagás, y se acredita<span>&nbsp;</span><strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">de 1 a 2 días hábiles</strong></td>
                                    </tr>
                                    <tr style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(222, 222, 222); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; vertical-align: baseline;">
                                        <td class="responsive-table-listing" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: rgb(222, 222, 222); border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center; left: 0px; width: 120px; background-color: rgb(255, 255, 255);">
                                            <ul style="box-sizing: border-box; font-family: inherit; margin: 10px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; list-style: disc inside; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.2;">
                                                <li class="paymentmethod-bapropagos" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px -800px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); width: 54px; height: 24px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">BaproPagos</li>
                                            </ul>
                                            <p style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , arial, helvetica, &quot; nimbus sans l&quot; , sans-serif; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.4; color: rgb(51, 51, 51);">
                                                <strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">En efectivo</strong>con<strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">&nbsp;Provincia NET</strong>:&nbsp;imprimí tu factura y acercate&nbsp;a pagar.
                                            </p>
                                        </td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px 0px 0px -1px; padding: 10px; border-top: 0px; border-right: 1px solid rgb(222, 222, 222); border-bottom: 1px solid rgb(222, 222, 222); border-left: none; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">1 pago.</td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: initial; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">Pagás, y se acredita<span>&nbsp;</span><strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">en 1 día hábil</strong></td>
                                    </tr>
                                    <tr style="box-sizing: border-box; font: inherit; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(222, 222, 222); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; vertical-align: baseline;">
                                        <td class="responsive-table-listing" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: rgb(222, 222, 222); border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center; left: 0px; width: 120px; background-color: rgb(255, 255, 255);">
                                            <ul class="payment-method-list" style="box-sizing: border-box; font-family: inherit; margin: 10px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; list-style: disc inside; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.2;">
                                                <li class="paymentmethod-account_money" style="box-sizing: border-box; font-family: inherit; margin: 2px 2px 2px 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.2; background-repeat: no-repeat; display: inline-block; overflow: hidden; text-indent: 100%; white-space: nowrap; background-position: 0px 0px; background-image: url(&quot;https://http2.mlstatic.com/secure/org-img/ui/payment-methods/1.7.4/ar/payment-methods-default.png&quot;); height: 20px; width: 72px; color: rgb(102, 102, 102); list-style-type: disc !important; list-style-position: inside;">Dinero en cuenta HomeFixPago</li>
                                            </ul>
                                            <p style="box-sizing: border-box; font-family: &quot; proxima nova&quot; , arial, helvetica, &quot; nimbus sans l&quot; , sans-serif; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 1.4; color: rgb(51, 51, 51);">
                                                <strong style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit;">Dinero en tu cuenta</strong>: tu dinero disponible en HomeFix se transfiere al instante a la cuenta del receptor.
                                            </p>
                                        </td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px 0px 0px -1px; padding: 10px; border-top: 0px; border-right: 1px solid rgb(222, 222, 222); border-bottom: 1px solid rgb(222, 222, 222); border-left: none; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">1 pago</td>
                                        <td class="responsive-table-exposition" style="box-sizing: border-box; font-family: inherit; margin: 0px; padding: 10px; border-width: 0px 1px 1px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: solid; border-left-style: initial; border-top-color: initial; border-right-color: rgb(222, 222, 222); border-bottom-color: rgb(222, 222, 222); border-left-color: initial; border-image: initial; outline: 0px; vertical-align: middle; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; height: 51px; text-align: center;">Se acredita instantáneamente</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
       
</div>

<style>
    .faqHeader {
        font-size: 27px;
        margin: 20px;
    }

    .panel-heading [data-toggle="collapse"]:after {
        font-family: 'Glyphicons Halflings';
        content: "\e072"; /* "play" icon */
        float: right;
        color: #F58723;
        font-size: 18px;
        line-height: 22px;
        /* rotate "play" icon from > (right arrow) to down arrow */
        -webkit-transform: rotate(-90deg);
        -moz-transform: rotate(-90deg);
        -ms-transform: rotate(-90deg);
        -o-transform: rotate(-90deg);
        transform: rotate(-90deg);
    }

    .panel-heading [data-toggle="collapse"].collapsed:after {
        /* rotate "play" icon from > (right arrow) to ^ (up arrow) */
        -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        -o-transform: rotate(90deg);
        transform: rotate(90deg);
        color: #454444;
    }
</style>

<!-- Bootstrap FAQ - END -->

</div>

</asp:Content>

